name: CI

on:
    push:
        branches: [master]
        tags: [v*]
jobs:
    build:
        name: Build

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install
              run: npm ci

            - name: Build
              run: npm run build

    lint:
       name: Lint

       runs-on: ubuntu-latest

       needs: build

       steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install
              run: npm ci

            - name: Build
              run: npm run build

            - name: Lint
              run: npm run lint